language: python

python:
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
  - python: '3.7'
    env: TOXENV=flake8

cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
