language: python
sudo: false
matrix:
  include:
  - python: '3.7'
    env: TOX_ENV=flake8
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox
install:
- pip install tox tox-travis coveralls
script:
- tox -e $TOX_ENV
after_success:
- coveralls
